export const staffData = [
  {
    id: 1,
    name: 'Valentina Reyes',
    role: 'QA Lead',
    bio: 'Especialista en automatización con más de 8 años en el sector fintech. Lideró la migración de pruebas manuales a Playwright en tres organizaciones, reduciendo el tiempo de regresión en un 65%. Apasionada por la cultura de calidad y el mentoring de equipos.',
    avatar: 'https://i.pravatar.cc/300?img=1',
    linkedin: 'https://linkedin.com',
    twitter: 'https://twitter.com',
  },
  {
    id: 2,
    name: 'Carlos Mendoza',
    role: 'SDET Senior',
    bio: 'Ingeniero de software con foco en testing de APIs REST y microservicios. Implementó frameworks de automatización en Cypress y K6 para equipos distribuidos. Certificado ISTQB Advanced y AWS Cloud Practitioner.',
    avatar: 'https://i.pravatar.cc/300?img=11',
    linkedin: 'https://linkedin.com',
    twitter: null,
  },
  {
    id: 3,
    name: 'Daniela Suárez',
    role: 'Fundadora / Organizadora',
    bio: 'Co-fundadora de la comunidad, con trayectoria en QA para banca digital y seguros. Experta en estrategias de testing en entornos regulados y metodologías ágiles. Speaker en conferencias regionales de software quality.',
    avatar: 'https://i.pravatar.cc/300?img=5',
    linkedin: 'https://linkedin.com',
    twitter: 'https://twitter.com',
  },
  {
    id: 4,
    name: 'Marcos Peña',
    role: 'Automatizador QA',
    bio: 'Desarrollador QA especializado en Selenium, TestNG y pipelines CI/CD con GitHub Actions. Contribuye a proyectos open-source de testing y dicta talleres sobre mejores prácticas de automatización.',
    avatar: 'https://i.pravatar.cc/300?img=15',
    linkedin: 'https://linkedin.com',
    twitter: null,
  },
  {
    id: 5,
    name: 'Isabela Ferreira',
    role: 'QA Analyst',
    bio: 'Analista con enfoque en testing exploratorio, gestión de defectos y métricas de calidad. Diseña planes de prueba para productos SaaS de alto tráfico. Actualmente especializada en accesibilidad y UX testing.',
    avatar: 'https://i.pravatar.cc/300?img=9',
    linkedin: 'https://linkedin.com',
    twitter: 'https://twitter.com',
  },
  {
    id: 6,
    name: 'Andrés Torres',
    role: 'Performance QA',
    bio: 'Especialista en pruebas de rendimiento con JMeter, Gatling y k6. Ha liderado proyectos de load testing para plataformas con más de un millón de usuarios concurrentes. Apasionado por la observabilidad y los dashboards de métricas.',
    avatar: 'https://i.pravatar.cc/300?img=18',
    linkedin: 'https://linkedin.com',
    twitter: 'https://twitter.com',
  },
  {
    id: 7,
    name: 'Lucía Herrera',
    role: 'Mobile QA Engineer',
    bio: 'Ingeniería de pruebas en aplicaciones iOS y Android con Appium y XCUITest. Colabora en proyectos de testing de apps financieras y de salud. Defensora de las pruebas de seguridad móvil en entornos OWASP.',
    avatar: 'https://i.pravatar.cc/300?img=3',
    linkedin: 'https://linkedin.com',
    twitter: null,
  },
  {
    id: 8,
    name: 'Rodrigo Campos',
    role: 'AI QA Engineer',
    bio: 'Explora el uso de IA generativa para optimizar ciclos de testing: generación de casos de prueba, análisis de logs y detección de patrones de fallo. Integra Claude, GPT y Gemini en pipelines de calidad modernos.',
    avatar: 'https://i.pravatar.cc/300?img=21',
    linkedin: 'https://linkedin.com',
    twitter: 'https://twitter.com',
  },
];
